{"uuid": "72ad6577-6c7a-4caf-9c33-ca2ef04303d0", "children": ["ebb10e87-ec70-4d5a-aae7-6a43f9550317"], "befores": [{"name": "test_base", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=81.0.4044.129)\n\n", "trace": "  File \"c:\\users\\gautamj\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\gautamj\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\gautamj\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\FinalFrameWork\\CredenceWeb_BaseTest\\BaseTest.py\", line 13, in test_base\n    self.driver.get(\"https://devconnect.credenceid.com/\")\n  File \"c:\\users\\gautamj\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\gautamj\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\gautamj\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1588850847740, "stop": 1588850860284}], "start": 1588850847740, "stop": 1588850860706}